AWSTemplateFormatVersion: '2010-09-09'
Description: Dave Merrills S3 Bucket CloudFormation Template

# Parameters:
#   BucketName:
#     Type: String
#     Description: The name of the S3 Bucket to create
#     default:  "david-merrills-bucket"

Resources:
  DavidsS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: david-merrills-bucket
      Tags:
        -
          Key: Creator
          Value: David Merrill
          Key: Date Created 
          Value: 11-17-2022
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Region: us-west-2
