AWSTemplateFormatVersion: '2010-09-09'
Description: Dave Merrills S3 Bucket CloudFormation Template

Parameters:
  BucketName:
    Type: String
    Description: The name of the S3 Bucket to create
    Default: !Join
        - "-"
        - - !Ref 'AWS::AccountId'
          - david-merrills-bucket-psuedo

Resources:
  DavidsS3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: !Ref BucketName
      Tags:
        -
          Key: Creator
          Value: David Merrill
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true