AWSTemplateFormatVersion: '2010-09-09'
Description: Dave Merrill Update IAM Role with Mangaged Policy

###====RESOURCES====##
Resources:
#  Lab3IAMRole:
#    Type: 'AWS::IAM::Role'
#    Properties:
#      AssumeRolePolicyDocument:
#        Version: "2012-10-17"
#        Statement:
#          - Effect: Allow
#            Principal:
#              Service:
#                - ec2.amazonaws.com
#            Action:
#              - 'sts:AssumeRole'
#      Path: /
#      RoleName: "DavidMerrill-ReadOnlyRole"
#      Description: "Role created for lab 3.1.1"

  Lab3IAMRole2:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      RoleName: "DavidMerrill-ReadOnlyRole2"
      Description: "This is a second Role created for Lab 3.1.3"


  Lab3IAMPolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: "DavidMerrill-ReadOnlyPolicy"
      PolicyDocument:
        {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Sid": "DavidMerrillReadOnlyRole",
              "Effect": "Allow",
              "Action": [
                "iam:GenerateCredentialReport",
                "iam:GetPolicyVersion",
                "iam:GetAccountPasswordPolicy",
                "iam:GetServiceLastAccessedDetailsWithEntities",
                "iam:GenerateServiceLastAccessedDetails",
                "iam:GetServiceLastAccessedDetails",
                "iam:GetGroup",
                "iam:GetContextKeysForPrincipalPolicy",
                "iam:GetServiceLinkedRoleDeletionStatus",
                "iam:SimulateCustomPolicy",
                "iam:SimulatePrincipalPolicy",
                "iam:GetAccountAuthorizationDetails",
                "iam:GetCredentialReport",
                "iam:GetSAMLProvider",
                "iam:GetServerCertificate",
                "iam:GetRole",
                "iam:GetInstanceProfile",
                "iam:GetPolicy",
                "iam:GetAccessKeyLastUsed",
                "iam:GetSSHPublicKey",
                "iam:GetContextKeysForCustomPolicy",
                "iam:GetUserPolicy",
                "iam:GetGroupPolicy",
                "iam:GetUser",
                "iam:GetOpenIDConnectProvider",
                "iam:GetRolePolicy"
              ],
              "Resource": "*"
            }
          ]
        }
      Roles:
#        - !Ref Lab3IAMRole1
        - !Ref Lab3IAMRole2
Outputs:
#  RoleId1:
#    Description: The logical ID of the IAM role
#    Value: !Ref Lab3IAMRole
  RoleId2:
    Description: The logical ID of the IAM role
    Value: !Ref Lab3IAMRole2
  PolicyId:
    Description: The logical ID of the IAM policy
    Value: !Ref Lab3IAMPolicy

#aws cloudformation update-stack \
#  --stack-name DavidMerrill-CreateUser-Lab3 \
#  --template-body file://3.1.3-CMP-ReUse.yml \
#  --profile labs-mfa \
#  --region us-west-2 \
#  --capabilities CAPABILITY_NAMED_IAM

## It didn't work.  It couldn't recreate a previous role.  Also the policy
## was already assigned and didn't need to be reassigned again.  I commented
## out the previous role and removed the policy role attachment to the original
## role and it worked.
