AWSTemplateFormatVersion: '2010-09-09'
Description: Dave Merrill Update IAM Role with Mangaged Policy

###====RESOURCES====##
Resources:
  Lab3IAMRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      RoleName: "DavidMerrill-ReadOnlyRole"

  Lab3IAMPolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: "DavidMerrill-ReadOnlyPolicy"
      PolicyDocument:
        {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Sid": "DavidMerrillReadOnlyRole",
              "Effect": "Allow",
              "Action": [
                "iam:GenerateCredentialReport",
                "iam:GetPolicyVersion",
                "iam:GetAccountPasswordPolicy",
                "iam:GetServiceLastAccessedDetailsWithEntities",
                "iam:GenerateServiceLastAccessedDetails",
                "iam:GetServiceLastAccessedDetails",
                "iam:GetGroup",
                "iam:GetContextKeysForPrincipalPolicy",
                "iam:GetServiceLinkedRoleDeletionStatus",
                "iam:SimulateCustomPolicy",
                "iam:SimulatePrincipalPolicy",
                "iam:GetAccountAuthorizationDetails",
                "iam:GetCredentialReport",
                "iam:GetSAMLProvider",
                "iam:GetServerCertificate",
                "iam:GetRole",
                "iam:GetInstanceProfile",
                "iam:GetPolicy",
                "iam:GetAccessKeyLastUsed",
                "iam:GetSSHPublicKey",
                "iam:GetContextKeysForCustomPolicy",
                "iam:GetUserPolicy",
                "iam:GetGroupPolicy",
                "iam:GetUser",
                "iam:GetOpenIDConnectProvider",
                "iam:GetRolePolicy"
              ],
              "Resource": "*"
            }
          ]
        }
      Roles:
        - !Ref Lab3IAMRole
Outputs:
  RoleId:
    Description: The logical ID of the IAM role
    Value: !Ref Lab3IAMRole
  PolicyId:
    Description: The logical ID of the IAM policy
    Value: !Ref Lab3IAMPolicy

#aws cloudformation update-stack \
#  --stack-name DavidMerrill-CreateUser-Lab3 \
#  --template-body file://3.1.2-CustomerManagedPolicy.yml \
#  --profile labs-mfa \
#  --region us-west-2 \
#  --capabilities CAPABILITY_NAMED_IAM
