AWSTemplateFormatVersion: '2010-09-09'
Description: Dave Merrill Create IAM Role with Trust Policy

###====RESOURCES====##
Resources:
  Lab3IAMRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: 'arn:aws:iam::324320755747:user/davidmerrilllab'
            Action: 'sts:AssumeRole'
      Path: /
      RoleName: "DavidMerrill-ReadOnlyRole-TrustUser"
      Description: "Role updated for lab 3.2.3"
      ManagedPolicyArns:
        - arn:aws:iam::324320755747:policy/ReadOnlyPolicy
        - arn:aws:iam::aws:policy/AmazonS3FullAccess

# aws cloudformation update-stack \
#  --stack-name DavidMerrill-CreateUser-Lab3-2 \
#  --template-body file://3.2.3-AddPriviledges.yml \
#  --profile labs-mfa \
#  --region us-west-2 \
#  --capabilities CAPABILITY_NAMED_IAM