AWSTemplateFormatVersion: '2010-09-09'
Description: Dave Merrill Create VPC and Private Subnet

###====RESOURCES====##
Resources:
###====CREATE VPC====##
  DavidMerrillVPC:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: 10.0.0.0/16
      Tags:
        - Key: user
          Value: david.merrill.labs
        - Key: stelligent-u-lesson
          Value: 04-VPC
        - Key: stelligent-u-lab
          Value: 1.1-CreateNewVPC-PrivateSubnet

###====CREATE PRIVATE SUBNET====##
  DavidMerrillSubnet:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref DavidMerrillVPC
      CidrBlock: 10.0.0.0/24
      Tags:
        - Key: user
          Value: david.merrill.labs
        - Key: stelligent-u-lesson
          Value: 04-VPC
        - Key: stelligent-u-lab
          Value: 1.1-CreateNewVPC-PrivateSubnet

###====OUTPUT VPC AND SUBNET====##
Outputs:
  VPCIDOutput:
    Description: Output ID of VPC
    Value: !Ref DavidMerrillVPC
  SubnetIDOutput:
    Description: Output ID of Subnet
    Value: !Ref DavidMerrillSubnet

# aws cloudformation create-stack \
#  --stack-name DavidMerrill-CreateVPC-Lab4-1 \
#  --template-body file://4.1.1-NewVPCPrivate.yml \
#  --profile labs-mfa \
#  --region us-west-2